config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  resources :messages
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  scope "(:locale)", locale: /en|vn/ do
    resources :users
    get "profile", to: "users#edit"
    post "update", to: "users#update"
    put "active_acc", to: "users#active_acc"
    get "listalluser", to: "users#listalluser"
    resources :departments
    resources :historyalls
    resources :histories
    get "historytudent", to: "histories#historystudent"
    resources :borrows
    put "accept_borrow", to: "borrows#accept_borrow"
    put "pay_book", to: "borrows#pay_book"
    get "mybook", to: "borrows#mybook"
    post "borrow_show", to: "borrows#create_by_show"
    get "borrows_book/:id", to: "borrows#index"
    resources :books
    # get "show_book/:id", to: "books#show_book"
    get "show_book_detail/:id", to: "books#show_book_detail"
    get "book_detail/:id", to: "books#book_detail"
    get "book_detail_student/:id", to: "books#book_detail_student"
    resources :publishers
    resources :types
    resources :authors
    resources :studytimes
    resources :equipment
    get "controller_equipment" => "equipment#index"
    get "new_equipment" => "equipment#new"
    root to: 'home#index'
    get "introduce", to: "home#introduce"
    get "/logout", to: "devise/registrations#destroy "
    namespace "admin" do
      root to: "equipment#index"
      resources :users
      resources :equipment
      resources :historyalls
    end
    namespace "api" do
      resources :authors
      resources :borrows
      resources :books
      resources :users
      resources :messages
      resources :firebases
      get "led_status", to: "firebases#led_status"
      post "updatestatus", to: "firebases#updatestatus"
      post "cart", to: "books#cart"
      post "cart_errors", to: "books#cart_errors"
      put "setpassword/:id", to: "users#setpassword"
      post "notices", to: "borrows#notices"
      post "sum_notices", to: "borrows#sum_notices"
      post "search_book", to: "books#search_book"
      post "addbook", to: "books#addbook"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # after_save :create_logs
  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)
    if @type.save
      render json:{notice: "Them thanh cong"}
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :department_id)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.slim
= form_for @type do |f|
  - if @type.errors.any?
    #error_explanation
      h2 = "#{pluralize(@type.errors.count, "error")} prohibited this type from being saved:"
      ul
        - @type.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/types/edit.html.slim
h1 Editing type

== render 'form'

=> link_to 'Show', @type
'|
=< link_to 'Back', types_path

app/views/types/index.html.slim
h1 Listing types

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @types.each do |type|
      tr
        td = type.name
        td = link_to 'Show', type
        td = link_to 'Edit', edit_type_path(type)
        td = link_to 'Destroy', type, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Type', new_type_path

app/views/types/new.html.slim
h1 New type

== render 'form'

= link_to 'Back', types_path

app/views/types/show.html.slim
p#notice = notice

p
  strong Name:
  = @type.name

=> link_to 'Edit', edit_type_path(@type)
'|
=< link_to 'Back', types_path