config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  resources :messages
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  scope "(:locale)", locale: /en|vn/ do
    resources :users
    get "profile", to: "users#edit"
    post "update", to: "users#update"
    put "active_acc", to: "users#active_acc"
    get "listalluser", to: "users#listalluser"
    resources :departments
    resources :historyalls
    resources :histories
    get "historytudent", to: "histories#historystudent"
    resources :borrows
    put "accept_borrow", to: "borrows#accept_borrow"
    put "pay_book", to: "borrows#pay_book"
    get "mybook", to: "borrows#mybook"
    post "borrow_show", to: "borrows#create_by_show"
    get "borrows_book/:id", to: "borrows#index"
    resources :books
    # get "show_book/:id", to: "books#show_book"
    get "show_book_detail/:id", to: "books#show_book_detail"
    get "book_detail/:id", to: "books#book_detail"
    get "book_detail_student/:id", to: "books#book_detail_student"
    resources :publishers
    resources :types
    resources :authors
    resources :studytimes
    resources :equipment
    get "controller_equipment" => "equipment#index"
    get "new_equipment" => "equipment#new"
    root to: 'home#index'
    get "introduce", to: "home#introduce"
    get "/logout", to: "devise/registrations#destroy "
    namespace "admin" do
      root to: "equipment#index"
      resources :users
      resources :equipment
      resources :historyalls
    end
    namespace "api" do
      resources :authors
      resources :borrows
      resources :books
      resources :users
      resources :messages
      resources :firebases
      get "led_status", to: "firebases#led_status"
      post "updatestatus", to: "firebases#updatestatus"
      post "cart", to: "books#cart"
      post "cart_errors", to: "books#cart_errors"
      put "setpassword/:id", to: "users#setpassword"
      post "notices", to: "borrows#notices"
      post "sum_notices", to: "borrows#sum_notices"
      post "search_book", to: "books#search_book"
      post "addbook", to: "books#addbook"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  after_save :create_logs

  private
  def create_logs
    mark = rand(1000..9999)
    col_logs = ["name", "website"]
    if name_changed? && !name_was.present?
      create_logs_with_action :update, col_logs,mark
    else
      create_logs_with_action :create, col_logs,mark
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)
    if @author.save
      render json:{notice: "Them thanh cong"}
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :website, :note)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :note
    = f.text_field :note
  .actions = f.submit

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

=> link_to 'Show', @author
'|
=< link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors

table
  thead
    tr
      th Name
      th Website
      th Note
      th
      th
      th

  tbody
    - @authors.each do |author|
      tr
        td = author.name
        td = author.website
        td = author.note
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
p#notice = notice

p
  strong Name:
  = @author.name
p
  strong Website:
  = @author.website
p
  strong Note:
  = @author.note

=> link_to 'Edit', edit_author_path(@author)
'|
=< link_to 'Back', authors_path