config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  resources :messages
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  scope "(:locale)", locale: /en|vn/ do
    resources :users
    get "profile", to: "users#edit"
    post "update", to: "users#update"
    put "active_acc", to: "users#active_acc"
    get "listalluser", to: "users#listalluser"
    resources :departments
    resources :historyalls
    resources :histories
    get "historytudent", to: "histories#historystudent"
    resources :borrows
    put "accept_borrow", to: "borrows#accept_borrow"
    put "pay_book", to: "borrows#pay_book"
    get "mybook", to: "borrows#mybook"
    post "borrow_show", to: "borrows#create_by_show"
    get "borrows_book/:id", to: "borrows#index"
    resources :books
    # get "show_book/:id", to: "books#show_book"
    get "show_book_detail/:id", to: "books#show_book_detail"
    get "book_detail/:id", to: "books#book_detail"
    get "book_detail_student/:id", to: "books#book_detail_student"
    resources :publishers
    resources :types
    resources :authors
    resources :studytimes
    resources :equipment
    get "controller_equipment" => "equipment#index"
    get "new_equipment" => "equipment#new"
    root to: 'home#index'
    get "introduce", to: "home#introduce"
    get "/logout", to: "devise/registrations#destroy "
    namespace "admin" do
      root to: "equipment#index"
      resources :users
      resources :equipment
      resources :historyalls
    end
    namespace "api" do
      resources :authors
      resources :borrows
      resources :books
      resources :users
      resources :messages
      resources :firebases
      get "led_status", to: "firebases#led_status"
      post "updatestatus", to: "firebases#updatestatus"
      post "cart", to: "books#cart"
      post "cart_errors", to: "books#cart_errors"
      put "setpassword/:id", to: "users#setpassword"
      post "notices", to: "borrows#notices"
      post "sum_notices", to: "borrows#sum_notices"
      post "search_book", to: "books#search_book"
      post "addbook", to: "books#addbook"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :book
  belongs_to :user
  # before_save :create_logs

  private
  def create_logs
    mark = rand(1000..9999)
    col_logs = ["book_id","user_id","allow"]
    if book_id_changed? && user_id_changed? && !book_id_was.present? && !user_id_was.present?
      create_logs_with_action :create, col_logs,mark
    else
      create_logs_with_action :update, col_logs,mark
    end
  end
end

app/controllers/api/borrows_controller.rb
module Api
  class BorrowsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      bookids = params[:bookids]
      array_errors = []
      bookids.split(",").each do |id|
        if Borrow.where(book_id: id, user_id: current_user.id).exists?
          array_errors.push(id)
        else
          amount = Book.find(id).amount
          if Borrow.where(book_id: id).pluck(:id).size >= amount
            array_errors.push(id)
          else
            @borrow = Borrow.new(book_id: id, user_id: current_user.id, allow: 0).save
          end
        end
      end
      render json: {data: array_errors}
    end
    def notices
      userid = params[:userid]
      borrow = Borrow.select(:id).where(user_id: userid, allow:0)
      render json:{data: borrow.size}
    end
    def sum_notices
      result = []
      if !params[:userid].nil?
        params[:userid].each do |userid|
          borrow = Borrow.select(:id).where(user_id: userid, allow:0)
          result.push(borrow.size)
        end
        render json:{data: result}
      else
        render json:{data: result}
      end
    end
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  before_action :check_staff, only: [:index]
  # before_action :check_equipment, only:[:index]

  # GET /borrows
  # GET /borrows.json
  def index
    @current_date = Time.zone.now.to_date
    @borrows = Borrow.order(:user_id).select("distinct(user_id)")
    if params[:id].present?
      @books = Borrow.where(user_id: params[:id])
      @amounts = Amount.all
    end
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
  end

  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows
  # POST /borrows.json
  def create
    getName = Book.where(id:getId["book_id"].to_i)
    getCount = Borrow.where(user_id:current_user.id).pluck(:user_id).size
    if Borrow.where(book_id: getId["book_id"].to_i, user_id: current_user.id).exists?
      getName.each do |getname|
        render json: {notice: t("borrow.exists", name: "#{getname.name}")}
      end
    else
      if getCount > 5
        render json: {notice: t("borrow.over")}
      else
        if check_exists_book(getId["book_id"].to_i) == true
          render json:{notice: "Sach da het so luong"}
        else
          @borrow = Borrow.new(borrow_params.merge(user_id: current_user.id, allow: false))
          getName.each do |getname|
            # respond_to do |format|
            if @borrow.save
              render json: {notice: t("borrow.success", name: "#{getname.name}")}
              # format.html { redirect_to "/books", notice: t("borrow.success", name: getname.name)}
            else
              render json: {notice: t("borrow.fail", name: "#{getname.name}")}
              # format.html { redirect_to "/books", notice: t("borrow.fail", name: getname.name)}
            end
            # end
          end
        end
      end
    end
  end

  def accept_borrow
    book_id = params[:book_id]
    user_id = params[:user_id]
    amount_id = params[:amount_id]
    borrow = Borrow.where(book_id: book_id, user_id: user_id)
    amount = Amount.find(amount_id)
    if borrow.update(allow: 1, staff_id_borrow: current_user.id)
      if amount.update(active: 1, user_id: user_id)
        render json:{notice: "OK"}
      else
        render json:{notice: "Fails"}
      end
    end
  end
  def pay_book
    book_id = params[:book_id]
    borrow_id = params[:borrow_id]
    amount_id = params[:amount_id]
    create_historys(current_user.id,borrow_id.to_i,amount_id.to_i)

  end
  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow.destroy
    respond_to do |format|
      format.html { redirect_to mybook_url, notice: t("mes.delete_success") }
      format.json { head :no_content }
    end
  end

  def mybook
    @borrowbooks = Borrow.where(user_id:current_user.id).order("created_at DESC")
    @amounts = Amount.all
    @histories = History.where(user_id:current_user.id).order("created_at DESC")
    @users = User.all
    @current_date = Time.zone.now.to_date
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrow_params
      params.require(:borrow).permit(:note, :user_id, :book_id)
    end
    def getId
      params.require(:borrow).permit(:book_id, :department_id)
    end
    def check_exists_book id
      amount = Book.find(id).amount
      if Borrow.where(book_id: id).pluck(:id).size >= amount
        return true
      end
    end
    def create_historys staff_id_pay,borrow_id,amount_id
      borrow = Borrow.where(id: borrow_id)
      borrow.each do |bor|
        his = History.new(staff_id_pay: staff_id_pay, amount_id: amount_id,  user_id: bor.user_id, borrow_time: bor.updated_at, pay_time: DateTime.current, book_id: bor.book_id, staff_id_borrow: bor.staff_id_borrow)
        his.save
      end
      Borrow.delete(borrow_id)
      amount = Amount.find(amount_id)
      if amount.update(active: 0, user_id: "")
        render json:{notice: "Tra sach thanh cong"}
      end
    end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
  def getBookCode book_id1,book_id2,code_book,current_user,user
    if book_id1 == book_id2&&current_user == user
      return code_book
    end
  end
  def check_status status
    if status == 0
      return I18n.t("book.processed")
    else
      return I18n.t("book.borrowed")
    end
  end
  def confirm val1,val2,active,book_user,amount_user
    str = "selected id=ds_select ds=1 disabled";
    if val1==val2 && active==true
      if book_user == amount_user
        return str
      end
    end
  end
  def getCode val1,val2,active,code,book_user,amount_user
    if val1==val2 && active == true
      if book_user == amount_user
        return code
      else
        return code
      end
    end
  end
  def check_code_amount amounts, bookid
    amounts.each do |ar|
      if ar.book_id == bookid
        return ar.code
      end
    end
  end
  def notice_accept_borrow borrow_users, user
    count = []
    borrow_users.each do |u|
      if u.user_id == user
        count.push(u.user_id)
        return count.size
      else
        return ""
      end
    end
  end
end

app/views/borrows/_form.html.slim
= form_for @borrow do |f|
  - if @borrow.errors.any?
    #error_explanation
      h2 = "#{pluralize(@borrow.errors.count, "error")} prohibited this borrow from being saved:"
      ul
        - @borrow.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :note
    = f.text_field :note
  .actions = f.submit

app/views/borrows/edit.html.slim
h1 Editing borrow

== render 'form'

=> link_to 'Show', @borrow
'|
=< link_to 'Back', borrows_path

app/views/borrows/index.html.slim
table#dataTableBorrow.table.table-striped.table-bordered.table-sm cellspacing="0" width="100%"
  thead
     tr
      th.th-sm #{I18n.t('borrow.code')}
      th.th-sm #{I18n.t('borrow.user_name')}
      /th.th-sm #{I18n.t('borrow.detail')}
  tbody
    - @borrows.each do |borrow|
      tr.detail.cursor data-bg="bg_#{borrow.user_id}" data-href="#{borrows_path}?id=#{borrow.user_id}"
        <td class="borr_notice borr_notice#{borrow.user_id}" data-userid = "#{borrow.user_id}">
          = borrow.user.code
          <small class="notice notice#{borrow.user_id}"></small>
        </td>
        td
          = borrow.user.name
        /td
        /  = link_to "#{I18n.t('borrow.detail')}", "/borrows_book/#{borrow.user_id}"
  tfoot
    tr
     th.th-sm #{I18n.t('borrow.code')}
     th.th-sm #{I18n.t('borrow.user_name')}
     /th.th-sm #{I18n.t('borrow.detail')}
- if @books.present?
  table#dataTableBook.table.table-striped.table-bordered.table-sm cellspacing="0" width="100%"
    thead
       tr
        th.th-sm #{I18n.t('borrow.book_code')}
        th.th-sm #{I18n.t('borrow.book_name')}
        th.th-sm #{I18n.t('borrow.date_borrow')}
        th.th-sm #{I18n.t('borrow.note')}
        th.th-sm #{I18n.t('borrow.allow')}
    tbody
      - @books.each do |b|
        tr
          td
            - amountidtem = 0
            <select class="select_code bookid#{b.book_id}" data-id="#{b.book_id}">
            option value="" data-bookid="0" mã sách
            - @amounts.each do |amount|
              - amountidtem = amount.id
              - if amount.book_id == b.book_id
                - if b.user_id == amount.user_id
                  <option class="code option#{amount.book_id}" name="code" value="#{amount.id}" data-bookid="#{amount.book_id}" #{confirm(amount.book_id,b.book_id,amount.active,b.user_id, amount.user_id)}>
                  = amount.code
                - else
                  - if amount.active == false
                    <option class="code option#{amount.book_id}" name="code" value="#{amount.id}" data-bookid="#{amount.book_id}" #{confirm(amount.book_id,b.book_id,amount.active,b.user_id, amount.user_id)}>
                    = amount.code
                </option>
            </select>
          td
            = b.book&.name
          td
            = format(b.updated_at)
          td.time_over.text-center
            = time_borrow(@current_date,format(b.updated_at),b.allow)
          td
            - if b.allow == 0
              <button class="btn btn-primary dis yes disbook#{b.book_id}" data-userid="#{b.user_id}" data-bookid="#{b.book_id}" disabled="disabled">#{I18n.t('borrow.y')}</button>
              <button class="btn btn-danger">#{I18n.t('borrow.n')}</button>
            - else
              <button class="btn btn-primary pay" data-userid="#{b.user_id}" data-bookid="#{b.book_id}" data-amountid="#{amountidtem}" data-borrowid="#{b.id}"">#{I18n.t('borrow.pa')}</button>
    tfoot
      tr
       th.th-sm #{I18n.t('borrow.book_code')}
       th.th-sm #{I18n.t('borrow.book_name')}
       th.th-sm #{I18n.t('borrow.date_borrow')}
       th.th-sm #{I18n.t('borrow.note')}
       th.th-sm #{I18n.t('borrow.allow')}

app/views/borrows/mybook.html.slim
h4.text-center #{I18n.t('mybook.waiting')}

table#dataTableProcess.table.table-striped.table-bordered.table-sm cellspacing="0" width="100%"
  thead
     tr
      th.th-sm #{I18n.t('mybook.code')}
      th.th-sm #{I18n.t('mybook.name')}
      th.th-sm #{I18n.t('mybook.date')}
      th.th-sm #{I18n.t('mybook.status')}
      th.th-sm
  tbody
    - @borrowbooks.each do |borrow|
      tr
        td
          - @amounts.each do |amount|
            - active =  amount.active
            = getBookCode(borrow.book_id,amount.book_id,amount.code,current_user.id,amount.user_id)
        td
          = borrow.book&.name
        td
          = format_datetime(borrow.updated_at)
        td
          = check_status(borrow.allow)
          div.time_over
            = time_borrow(@current_date, format(borrow.updated_at),borrow.allow)
        td
          /<button class="btn btn-danger"></button>
          - if borrow.allow == 0
            = link_to "#{I18n.t('mybook.delete')}", borrow, data: { confirm: "#{t("mes.delete")}" }, method: :delete, class: "nav-link"
  tfoot
    tr
      th.th-sm #{I18n.t('mybook.code')}
      th.th-sm #{I18n.t('mybook.name')}
      th.th-sm #{I18n.t('mybook.date')}
      th.th-sm #{I18n.t('mybook.status')}
      th.th-sm
h4.text-center #{I18n.t('mybook.borrowhistory')}

table#dataTableHistory.table.table-striped.table-bordered.table-sm cellspacing="0" width="100%"
  thead
     tr
      th.th-sm #{I18n.t('mybook.code')}
      th.th-sm #{I18n.t('mybook.name')}
      th.th-sm #{I18n.t('mybook.borrower')}
      th.th-sm #{I18n.t('mybook.receiver')}
      th.th-sm #{I18n.t('mybook.date_borrow')}
      th.th-sm #{I18n.t('mybook.date_pay')}
      th.th-sm #{I18n.t('mybook.status')}
  tbody
    - @histories.each do |borrow|
      tr
        td
          = borrow.amount&.code
        td
          = borrow.book&.name
        td
          = get_staff(@users,borrow.staff_id_borrow)
        td
          = get_staff(@users,borrow.staff_id_pay)
        td
          = format_datetime(borrow.borrow_time)
        td
          = format_datetime(borrow.pay_time)
        td
          = check_staus_history(borrow.status)

  tfoot
    tr
      th.th-sm #{I18n.t('mybook.code')}
      th.th-sm #{I18n.t('mybook.name')}
      th.th-sm #{I18n.t('mybook.borrower')}
      th.th-sm #{I18n.t('mybook.receiver')}
      th.th-sm #{I18n.t('mybook.date_borrow')}
      th.th-sm #{I18n.t('mybook.date_pay')}
      th.th-sm #{I18n.t('mybook.status')}

app/views/borrows/new.html.slim
h1 New borrow

== render 'form'

= link_to 'Back', borrows_path

app/views/borrows/show.html.slim
p#notice = notice

p
  strong Note:
  = @borrow.note

=> link_to 'Edit', edit_borrow_path(@borrow)
'|
=< link_to 'Back', borrows_path